version: "{build}"

os: Visual Studio 2015

configuration: Release

platform:
  - x86
  - x64

branches:
  only:
    - master

test: off

before_build:
  - cmd: nuget restore

build:
  parallel: true
  verbosity: detailed

after_build:
  - ps: Copy-Item "WinLLDPService\build\paths.ps1.example" "WinLLDPService\build\paths.ps1"
  - ps: WinLLDPService\build\build.ps1 "$Env:PLATFORM"

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug

cache:
  - packages -> **\packages.config
